version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  rdns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rdns
    privileged: true
    environment:
      - RDNS_HTTP_PORT=8080
      - RDNS_LOG_LEVEL=DEBUG
      - RDNS_RESOLVERS=getaddrinfo,packet
      - RDNS_REDIS_ADDRESS=localhost:6379
      - RDNS_REDIS_USER=
      - RDNS_REDIS_PASSWORD=
    network_mode: "host" # required for resolution via XDP packet
    depends_on:
      - redis
    ports:
      - "8080:8080"

volumes:
  redis-data:
    driver: local